### ISSUE TITLE
Module in Git

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#122]
## Need expression

when a CET, CRT, service, endpoint, filter, notification,... is created it should be assigned to a module (there is a default meveo module).

Each module is associated to a git repository that serves as secondary storage (we maintains the entities in DB).
This git repo is what is zipped when a module is serialized for download, upload.
when downloading a module from a remote instance clone the repo (but there is still an installation procedure).

## Technical analysis

- [x] #248 : Add "path" attribute to @ModuleItem
- [x] #256 : Add "gitRepository" attribute to MeveoModule.
- [x] #257 : One entity can belongs to only one module
- [x] #258 : Services for moving an entity from a module to an other
- [x] #259, #260, #261 : Implement the previous services for the scripts, endpoints, cet and cfts
- [x] #270 : Modify installation of a module from a json file
- [x] #271 : Handle installation of a module from a git link
- [x] Script installation from git link : special case to use the source code from the .java file
- [x] ~~Handle creation and update of module items in corresponding module repositories~~ (handled in #262 for creation and #259 to #261 for update)
- [x] #357: Modify tree view of meveo modules 
- [x] #376
- [x] #377
- [x] Manually create remote repositories for existing modules
- [ ]  #645
- [x] Generate a pom.xml file for each module (using group id and artifact id from module information
- [x] Serve a zipped file of module via the MavenServlet
- [x] #262 : Create default "Meveo" module
- [x] Handle installation of a module from a zipped file (keep old system which reads a json file but deprecate it)
- [ ] Handle release of new version of module

**Comment by ClementBareth** [comment]
@smichea if entity is always link to one module, it means it is an exclusive relationship => an entity can't be in several repositories. Right ?

**Comment by smichea** [comment]
Yes an entity belongs to one module only

**Comment by ClementBareth** [comment]
We need to modify the repartition of the customFieldTemplates json to put them in separated folders per CETs
