### ISSUE TITLE
Allow user to choose to include files when adding a git repo to a module

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#194]
**Is your feature request related to a problem? Please describe.**
When adding a git repository to a module, prompt the user to choose whether to include the repository files or not

**Describe the solution you'd like**
After choosing the git repository, a dialog prompt should appear asking the user to include the files or not.

**Describe alternatives you've considered**
Currently, after the repository is added to the module, the user has to manually remove the files from the Module Files section.

**Additional context**
This is an enhancement for #142 

### Task list
- [ ] Add function `getAddToModuleParameters : Map<String, Class>` to `BaseCrudApi` that returns the parameters to display to the user
- [ ] The previous function should be called before the action of adding entity to module
  - [ ] In the module GUI
  - [ ] In the addToModule pop-up 
- [ ] Add new parameter "option" to BaseCrudApi#addToModule
  - This parameter will be a Map<String, Object>, where the key would correspond to a parameter name that should be mapped by the implementation
- [ ] Map additional parameter to the getAddToModuleParameters of the BaseCrudApi impl when adding entity to module from REST API
  - Take those parameters from query or body ? If from body, use JSON or FormParams ?

**Comment by ClementBareth** [comment]
- [ ] Modify export service to add the fileExports parameter
- [ ] Create the GUI dialog
- [ ] Handle parameters from REST API

**Comment by ClementBareth** [comment]
The dialog will only be displayed on module export action
